name: Build

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install Node Packages
        run: yarn

      - name: Install pandoc
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: pandoc
          version: 1.0

      - name: Restore File Updated Time
        run: git ls-files -z | while read -d '' path; do touch -d "$(git log -1 --format="@%ct" "$path")" "$path"; done
        working-directory: ./source

      - name: Generate Files
        run: ./node_modules/.bin/hexo g

      - name: Deploy to Cloudflare Pages Productive
        if: github.ref == 'refs/heads/master'
        uses: cloudflare/pages-action@v1.1.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: e40ca42475e880f2bb8fef31bc321e4c
          projectName: blog-krishu-moe
          directory: public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Deploy to Cloudflare Pages Previewing
        if: github.ref != 'refs/heads/master'
        uses: cloudflare/pages-action@v1.1.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: e40ca42475e880f2bb8fef31bc321e4c
          projectName: blog-krishu-moe
          directory: public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
